language: bash
services: docker

env:
  - VERSION=latest
  - VERSION=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="marceloalmeida/serf-rancher:${VERSION}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

# vim:set et ts=2 sw=2:
